## Imports

In [38]:
import numpy as np
import pandas as pd
import json

import torch

from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers import AutoModelForSequenceClassification
from transformers import DataCollatorWithPadding

import evaluate

from transformers import TrainingArguments
from transformers import Trainer

## Setup

In [2]:
MODEL_NAME = "google-bert/bert-base-uncased"
SEED = 42
NUM_LABELS = 3

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

PyTorch version: 2.14.0+cu130
CUDA available: True
GPU: NVIDIA GeForce RTX 5080 Laptop GPU

## Load MNLI Dataset

In [3]:
mnli = load_dataset("nyu-mll/glue", "mnli")

train_dataset = mnli["train"]
val_matched = mnli["validation_matched"]
val_mismatched = mnli["validation_mismatched"]

print("Train:", len(train_dataset))
print("Validation matched:", len(val_matched))
print("Validation mismatched:", len(val_mismatched))

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Train: 392702
Validation matched: 9815
Validation mismatched: 9832

In [4]:
mnli

DatasetDict({
    train: Dataset({
        features: ['premise', 'hypothesis', 'label', 'idx'],
        num_rows: 392702
    })
    validation_matched: Dataset({
        features: ['premise', 'hypothesis', 'label', 'idx'],
        num_rows: 9815
    })
    validation_mismatched: Dataset({
        features: ['premise', 'hypothesis', 'label', 'idx'],
        num_rows: 9832
    })
    test_matched: Dataset({
        features: ['premise', 'hypothesis', 'label', 'idx'],
        num_rows: 9796
    })
    test_mismatched: Dataset({
        features: ['premise', 'hypothesis', 'label', 'idx'],
        num_rows: 9847
    })
})

## BERT Tokenizer

In [5]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

### Sample

In [6]:
example = train_dataset[0]

print("Premise:")
print(example["premise"])

print("\nHypothesis:")
print(example["hypothesis"])

Premise:
Conceptually cream skimming has two basic dimensions - product and geography.

Hypothesis:
Product and geography are what make cream skimming work.

In [7]:
encoded = tokenizer(
    example["premise"],
    example["hypothesis"],
    truncation=True
)

encoded

{'input_ids': [101, 17158, 2135, 6949, 8301, 25057, 2038, 2048, 3937, 9646, 1011, 4031, 1998, 10505, 1012, 102, 4031, 1998, 10505, 2024, 2054, 2191, 6949, 8301, 25057, 2147, 1012, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [8]:
tokens = tokenizer.convert_ids_to_tokens(encoded["input_ids"])
tokens

['[CLS]',
 'conceptual',
 '##ly',
 'cream',
 'ski',
 '##mming',
 'has',
 'two',
 'basic',
 'dimensions',
 '-',
 'product',
 'and',
 'geography',
 '.',
 '[SEP]',
 'product',
 'and',
 'geography',
 'are',
 'what',
 'make',
 'cream',
 'ski',
 '##mming',
 'work',
 '.',
 '[SEP]']

## Tokenization Function

In [9]:
MAX_LENGTH = 128

def tokenize_function(examples):
    return tokenizer(
        examples["premise"],
        examples["hypothesis"],
        truncation=True,
        max_length=MAX_LENGTH,
    )

## Tokenize Dataset

In [10]:
tokenized_mnli = mnli.map(
    tokenize_function,
    batched=True
)

In [11]:
tokenized_mnli

DatasetDict({
    train: Dataset({
        features: ['premise', 'hypothesis', 'label', 'idx', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 392702
    })
    validation_matched: Dataset({
        features: ['premise', 'hypothesis', 'label', 'idx', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 9815
    })
    validation_mismatched: Dataset({
        features: ['premise', 'hypothesis', 'label', 'idx', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 9832
    })
    test_matched: Dataset({
        features: ['premise', 'hypothesis', 'label', 'idx', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 9796
    })
    test_mismatched: Dataset({
        features: ['premise', 'hypothesis', 'label', 'idx', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 9847
    })
})

In [12]:
tokenized_mnli["train"][0]

{'premise': 'Conceptually cream skimming has two basic dimensions - product and geography.',
 'hypothesis': 'Product and geography are what make cream skimming work. ',
 'label': 1,
 'idx': 0,
 'input_ids': [101,
  17158,
  2135,
  6949,
  8301,
  25057,
  2038,
  2048,
  3937,
  9646,
  1011,
  4031,
  1998,
  10505,
  1012,
  102,
  4031,
  1998,
  10505,
  2024,
  2054,
  2191,
  6949,
  8301,
  25057,
  2147,
  1012,
  102],
 'token_type_ids': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 'attention_mask': [1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1]}

In [13]:
print("Premise:")
print(tokenized_mnli["train"][0]["premise"])

print("\nHypothesis:")
print(tokenized_mnli["train"][0]["hypothesis"])

print("\nLabel:")
print(tokenized_mnli["train"][0]["label"])

print("\nTokens:")
print(
    tokenizer.convert_ids_to_tokens(
        tokenized_mnli["train"][0]["input_ids"]
    )
)

Premise:
Conceptually cream skimming has two basic dimensions - product and geography.

Hypothesis:
Product and geography are what make cream skimming work.

Label:
1

Tokens:
['[CLS]', 'conceptual', '##ly', 'cream', 'ski', '##mming', 'has', 'two', 'basic', 'dimensions', '-', 'product', 'and', 'geography', '.', '[SEP]', 'product', 'and', 'geography', 'are', 'what', 'make', 'cream', 'ski', '##mming', 'work', '.', '[SEP]']

### Checking length

In [14]:
lengths = [
    len(
        tokenizer(
            premise,
            hypothesis,
            truncation=False
        )["input_ids"]
    )
    for premise, hypothesis in zip(
        mnli["train"]["premise"],
        mnli["train"]["hypothesis"]
    )
]

num_over_128 = sum(length > 128 for length in lengths)

print(f"Examples > 128 tokens: {num_over_128:,}")
print(f"Percentage truncated: {num_over_128 / len(lengths) * 100:.2f}%")
print(f"Longest example: {max(lengths)} tokens")

Examples > 128 tokens: 1,169
Percentage truncated: 0.30%
Longest example: 444 tokens

## Build FP32 BERT Classifier

In [15]:
label_names = mnli["train"].features["label"].names

id2label = {
    i: label
    for i, label in enumerate(label_names)
}

label2id = {
    label: i
    for i, label in enumerate(label_names)
}

print(id2label)
print(label2id)

{0: 'entailment', 1: 'neutral', 2: 'contradiction'}
{'entailment': 0, 'neutral': 1, 'contradiction': 2}

In [16]:
model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=3,
    id2label=id2label,
    label2id=label2id,
)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: google-bert/bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [17]:
print(model.config)

BertConfig {
  "add_cross_attention": false,
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": null,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "id2label": {
    "0": "entailment",
    "1": "neutral",
    "2": "contradiction"
  },
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "is_decoder": false,
  "label2id": {
    "contradiction": 2,
    "entailment": 0,
    "neutral": 1
  },
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "tie_word_embeddings": true,
  "transformers_version": "5.17.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

In [18]:
print(model.classifier)

Linear(in_features=768, out_features=3, bias=True)

## Dynamic Padding

In [19]:
data_collator = DataCollatorWithPadding(
    tokenizer=tokenizer
)

## Defining Evaluation

In [20]:
accuracy_metric = evaluate.load("accuracy")

In [21]:
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)

    return accuracy_metric.compute(
        predictions=predictions,
        references=labels
    )

## Hyperparameters

In [22]:
LEARNING_RATE = 2e-5
BATCH_SIZE = 32
NUM_EPOCHS = 3
#WEIGHT_DECAY = 0.01

In [23]:
training_args = TrainingArguments(
    output_dir="../models/fp32",

    learning_rate=LEARNING_RATE,

    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,

    num_train_epochs=NUM_EPOCHS,
    #weight_decay=WEIGHT_DECAY,

    eval_strategy="epoch",
    save_strategy="epoch",

    logging_steps=500,

    seed=SEED
)

## Trainer

In [24]:
trainer = Trainer(
    model=model,
    args=training_args,

    train_dataset=tokenized_mnli["train"],
    eval_dataset=tokenized_mnli["validation_matched"],

    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

In [25]:
torch.cuda.empty_cache()
torch.cuda.reset_peak_memory_stats()

In [28]:
train_result = trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [29]:
peak_memory = torch.cuda.max_memory_allocated() / 1024**3

print(f"Peak GPU memory: {peak_memory:.2f} GB")

Peak GPU memory: 3.74 GB

In [30]:
train_result

TrainOutput(global_step=36816, training_loss=0.36402171697372043, metrics={'train_runtime': 4931.6992, 'train_samples_per_second': 238.884, 'train_steps_per_second': 7.465, 'total_flos': 5.433814602886219e+16, 'train_loss': 0.36402171697372043, 'epoch': 3.0})

In [31]:
trainer.state.log_history

[{'loss': 0.8490717163085938,
  'grad_norm': 13.078166007995605,
  'learning_rate': 1.972892220773577e-05,
  'epoch': 0.04074315514993481,
  'step': 500},
 {'loss': 0.6611880493164063,
  'grad_norm': 6.243322849273682,
  'learning_rate': 1.945730117340287e-05,
  'epoch': 0.08148631029986962,
  'step': 1000},
 {'loss': 0.6065051879882812,
  'grad_norm': 6.863010406494141,
  'learning_rate': 1.9185680139069973e-05,
  'epoch': 0.12222946544980444,
  'step': 1500},
 {'loss': 0.5907832641601563,
  'grad_norm': 7.787161350250244,
  'learning_rate': 1.891405910473707e-05,
  'epoch': 0.16297262059973924,
  'step': 2000},
 {'loss': 0.5654505004882813,
  'grad_norm': 10.66730785369873,
  'learning_rate': 1.8642438070404173e-05,
  'epoch': 0.20371577574967406,
  'step': 2500},
 {'loss': 0.5397528686523437,
  'grad_norm': 6.1487507820129395,
  'learning_rate': 1.8370817036071274e-05,
  'epoch': 0.24445893089960888,
  'step': 3000},
 {'loss': 0.5415055541992188,
  'grad_norm': 6.344176769256592,
  'learning_rate': 1.8099196001738376e-05,
  'epoch': 0.28520208604954367,
  'step': 3500},
 {'loss': 0.5163956909179688,
  'grad_norm': 9.621498107910156,
  'learning_rate': 1.7827574967405478e-05,
  'epoch': 0.3259452411994785,
  'step': 4000},
 {'loss': 0.5208818359375,
  'grad_norm': 9.504307746887207,
  'learning_rate': 1.755595393307258e-05,
  'epoch': 0.3666883963494133,
  'step': 4500},
 {'loss': 0.5056903686523437,
  'grad_norm': 6.1898088455200195,
  'learning_rate': 1.728433289873968e-05,
  'epoch': 0.4074315514993481,
  'step': 5000},
 {'loss': 0.499910888671875,
  'grad_norm': 7.274782657623291,
  'learning_rate': 1.701271186440678e-05,
  'epoch': 0.44817470664928294,
  'step': 5500},
 {'loss': 0.49672021484375,
  'grad_norm': 6.1878228187561035,
  'learning_rate': 1.674109083007388e-05,
  'epoch': 0.48891786179921776,
  'step': 6000},
 {'loss': 0.491934814453125,
  'grad_norm': 4.778132438659668,
  'learning_rate': 1.6469469795740983e-05,
  'epoch': 0.5296610169491526,
  'step': 6500},
 {'loss': 0.47633740234375,
  'grad_norm': 5.680876731872559,
  'learning_rate': 1.6197848761408085e-05,
  'epoch': 0.5704041720990873,
  'step': 7000},
 {'loss': 0.48006982421875,
  'grad_norm': 5.832892894744873,
  'learning_rate': 1.5926227727075186e-05,
  'epoch': 0.6111473272490222,
  'step': 7500},
 {'loss': 0.48210272216796873,
  'grad_norm': 4.699972629547119,
  'learning_rate': 1.5654606692742288e-05,
  'epoch': 0.651890482398957,
  'step': 8000},
 {'loss': 0.4719773559570313,
  'grad_norm': 6.536838531494141,
  'learning_rate': 1.538298565840939e-05,
  'epoch': 0.6926336375488917,
  'step': 8500},
 {'loss': 0.47841238403320313,
  'grad_norm': 5.569195747375488,
  'learning_rate': 1.511136462407649e-05,
  'epoch': 0.7333767926988266,
  'step': 9000},
 {'loss': 0.46125350952148436,
  'grad_norm': 6.933944225311279,
  'learning_rate': 1.4839743589743592e-05,
  'epoch': 0.7741199478487614,
  'step': 9500},
 {'loss': 0.46006500244140625,
  'grad_norm': 7.117440700531006,
  'learning_rate': 1.4568122555410693e-05,
  'epoch': 0.8148631029986962,
  'step': 10000},
 {'loss': 0.468535888671875,
  'grad_norm': 7.829463005065918,
  'learning_rate': 1.4296501521077792e-05,
  'epoch': 0.855606258148631,
  'step': 10500},
 {'loss': 0.4583150634765625,
  'grad_norm': 7.505943775177002,
  'learning_rate': 1.4024880486744893e-05,
  'epoch': 0.8963494132985659,
  'step': 11000},
 {'loss': 0.4593179016113281,
  'grad_norm': 6.929636478424072,
  'learning_rate': 1.3753259452411995e-05,
  'epoch': 0.9370925684485006,
  'step': 11500},
 {'loss': 0.4488466491699219,
  'grad_norm': 6.36875057220459,
  'learning_rate': 1.3481638418079097e-05,
  'epoch': 0.9778357235984355,
  'step': 12000},
 {'eval_loss': 0.4254729449748993,
  'eval_accuracy': 0.8361691288843607,
  'eval_runtime': 15.1953,
  'eval_samples_per_second': 645.923,
  'eval_steps_per_second': 20.204,
  'epoch': 1.0,
  'step': 12272},
 {'loss': 0.40171994018554685,
  'grad_norm': 6.117507457733154,
  'learning_rate': 1.3210017383746199e-05,
  'epoch': 1.0185788787483703,
  'step': 12500},
 {'loss': 0.3376209716796875,
  'grad_norm': 5.808748245239258,
  'learning_rate': 1.29383963494133e-05,
  'epoch': 1.0593220338983051,
  'step': 13000},
 {'loss': 0.344445068359375,
  'grad_norm': 7.028751850128174,
  'learning_rate': 1.2666775315080402e-05,
  'epoch': 1.1000651890482398,
  'step': 13500},
 {'loss': 0.3455759887695313,
  'grad_norm': 7.790998458862305,
  'learning_rate': 1.23951542807475e-05,
  'epoch': 1.1408083441981747,
  'step': 14000},
 {'loss': 0.35145318603515624,
  'grad_norm': 3.000354290008545,
  'learning_rate': 1.2123533246414602e-05,
  'epoch': 1.1815514993481095,
  'step': 14500},
 {'loss': 0.3408988952636719,
  'grad_norm': 6.786212921142578,
  'learning_rate': 1.1851912212081704e-05,
  'epoch': 1.2222946544980444,
  'step': 15000},
 {'loss': 0.34495278930664064,
  'grad_norm': 6.116368293762207,
  'learning_rate': 1.1580291177748805e-05,
  'epoch': 1.263037809647979,
  'step': 15500},
 {'loss': 0.3428761901855469,
  'grad_norm': 7.203455448150635,
  'learning_rate': 1.1308670143415907e-05,
  'epoch': 1.303780964797914,
  'step': 16000},
 {'loss': 0.3450167541503906,
  'grad_norm': 8.420942306518555,
  'learning_rate': 1.1037049109083009e-05,
  'epoch': 1.3445241199478488,
  'step': 16500},
 {'loss': 0.35009347534179686,
  'grad_norm': 8.840088844299316,
  'learning_rate': 1.076542807475011e-05,
  'epoch': 1.3852672750977835,
  'step': 17000},
 {'loss': 0.34087322998046876,
  'grad_norm': 6.0767436027526855,
  'learning_rate': 1.049380704041721e-05,
  'epoch': 1.4260104302477183,
  'step': 17500},
 {'loss': 0.3384752197265625,
  'grad_norm': 5.704891204833984,
  'learning_rate': 1.022218600608431e-05,
  'epoch': 1.4667535853976532,
  'step': 18000},
 {'loss': 0.3383680419921875,
  'grad_norm': 9.960634231567383,
  'learning_rate': 9.950564971751412e-06,
  'epoch': 1.5074967405475879,
  'step': 18500},
 {'loss': 0.33607302856445315,
  'grad_norm': 5.205428600311279,
  'learning_rate': 9.678943937418514e-06,
  'epoch': 1.548239895697523,
  'step': 19000},
 {'loss': 0.3419884033203125,
  'grad_norm': 4.609706878662109,
  'learning_rate': 9.407322903085616e-06,
  'epoch': 1.5889830508474576,
  'step': 19500},
 {'loss': 0.3403772277832031,
  'grad_norm': 5.631674289703369,
  'learning_rate': 9.135701868752716e-06,
  'epoch': 1.6297262059973925,
  'step': 20000},
 {'loss': 0.3362467346191406,
  'grad_norm': 6.007964134216309,
  'learning_rate': 8.864080834419818e-06,
  'epoch': 1.6704693611473274,
  'step': 20500},
 {'loss': 0.3371645202636719,
  'grad_norm': 9.533254623413086,
  'learning_rate': 8.59245980008692e-06,
  'epoch': 1.711212516297262,
  'step': 21000},
 {'loss': 0.333902587890625,
  'grad_norm': 14.760737419128418,
  'learning_rate': 8.32083876575402e-06,
  'epoch': 1.7519556714471969,
  'step': 21500},
 {'loss': 0.3321210327148437,
  'grad_norm': 4.551612854003906,
  'learning_rate': 8.049217731421121e-06,
  'epoch': 1.7926988265971318,
  'step': 22000},
 {'loss': 0.3325196838378906,
  'grad_norm': 13.336743354797363,
  'learning_rate': 7.777596697088223e-06,
  'epoch': 1.8334419817470664,
  'step': 22500},
 {'loss': 0.3341304931640625,
  'grad_norm': 11.482847213745117,
  'learning_rate': 7.5059756627553245e-06,
  'epoch': 1.8741851368970013,
  'step': 23000},
 {'loss': 0.3368756103515625,
  'grad_norm': 3.097480535507202,
  'learning_rate': 7.234354628422425e-06,
  'epoch': 1.9149282920469362,
  'step': 23500},
 {'loss': 0.3398858947753906,
  'grad_norm': 3.763726234436035,
  'learning_rate': 6.962733594089527e-06,
  'epoch': 1.9556714471968708,
  'step': 24000},
 {'loss': 0.3268632507324219,
  'grad_norm': 4.930908203125,
  'learning_rate': 6.691112559756629e-06,
  'epoch': 1.996414602346806,
  'step': 24500},
 {'eval_loss': 0.4336777329444885,
  'eval_accuracy': 0.8420784513499745,
  'eval_runtime': 15.9402,
  'eval_samples_per_second': 615.739,
  'eval_steps_per_second': 19.26,
  'epoch': 2.0,
  'step': 24544},
 {'loss': 0.2507157897949219,
  'grad_norm': 9.801762580871582,
  'learning_rate': 6.419491525423729e-06,
  'epoch': 2.0371577574967406,
  'step': 25000},
 {'loss': 0.22940911865234376,
  'grad_norm': 11.612812995910645,
  'learning_rate': 6.1478704910908306e-06,
  'epoch': 2.077900912646675,
  'step': 25500},
 {'loss': 0.23722981262207032,
  'grad_norm': 8.542718887329102,
  'learning_rate': 5.876249456757932e-06,
  'epoch': 2.1186440677966103,
  'step': 26000},
 {'loss': 0.2424527587890625,
  'grad_norm': 6.014408588409424,
  'learning_rate': 5.604628422425034e-06,
  'epoch': 2.159387222946545,
  'step': 26500},
 {'loss': 0.2335845947265625,
  'grad_norm': 3.9352197647094727,
  'learning_rate': 5.333007388092134e-06,
  'epoch': 2.2001303780964796,
  'step': 27000},
 {'loss': 0.23349708557128906,
  'grad_norm': 7.637985706329346,
  'learning_rate': 5.061386353759236e-06,
  'epoch': 2.2408735332464147,
  'step': 27500},
 {'loss': 0.24054376220703125,
  'grad_norm': 8.152220726013184,
  'learning_rate': 4.789765319426337e-06,
  'epoch': 2.2816166883963493,
  'step': 28000},
 {'loss': 0.22097752380371094,
  'grad_norm': 9.632610321044922,
  'learning_rate': 4.518144285093438e-06,
  'epoch': 2.322359843546284,
  'step': 28500},
 {'loss': 0.23433668518066406,
  'grad_norm': 7.661739826202393,
  'learning_rate': 4.246523250760539e-06,
  'epoch': 2.363102998696219,
  'step': 29000},
 {'loss': 0.22776852416992188,
  'grad_norm': 10.940817832946777,
  'learning_rate': 3.974902216427641e-06,
  'epoch': 2.4038461538461537,
  'step': 29500},
 {'loss': 0.236477294921875,
  'grad_norm': 6.024930000305176,
  'learning_rate': 3.703281182094742e-06,
  'epoch': 2.444589308996089,
  'step': 30000},
 {'loss': 0.23382933044433593,
  'grad_norm': 5.172402381896973,
  'learning_rate': 3.4316601477618427e-06,
  'epoch': 2.4853324641460235,
  'step': 30500},
 {'loss': 0.2309245300292969,
  'grad_norm': 10.89422607421875,
  'learning_rate': 3.1600391134289444e-06,
  'epoch': 2.526075619295958,
  'step': 31000},
 {'loss': 0.22956613159179687,
  'grad_norm': 13.834132194519043,
  'learning_rate': 2.8884180790960453e-06,
  'epoch': 2.5668187744458932,
  'step': 31500},
 {'loss': 0.2253853302001953,
  'grad_norm': 7.029417991638184,
  'learning_rate': 2.616797044763147e-06,
  'epoch': 2.607561929595828,
  'step': 32000},
 {'loss': 0.23612342834472655,
  'grad_norm': 5.216897010803223,
  'learning_rate': 2.345176010430248e-06,
  'epoch': 2.648305084745763,
  'step': 32500},
 {'loss': 0.23280511474609375,
  'grad_norm': 9.318384170532227,
  'learning_rate': 2.073554976097349e-06,
  'epoch': 2.6890482398956976,
  'step': 33000},
 {'loss': 0.23510774230957032,
  'grad_norm': 12.735735893249512,
  'learning_rate': 1.8019339417644505e-06,
  'epoch': 2.7297913950456323,
  'step': 33500},
 {'loss': 0.2388759307861328,
  'grad_norm': 2.3942787647247314,
  'learning_rate': 1.5303129074315518e-06,
  'epoch': 2.770534550195567,
  'step': 34000},
 {'loss': 0.23643939208984374,
  'grad_norm': 9.681511878967285,
  'learning_rate': 1.2586918730986528e-06,
  'epoch': 2.811277705345502,
  'step': 34500},
 {'loss': 0.2206165771484375,
  'grad_norm': 5.487811088562012,
  'learning_rate': 9.870708387657541e-07,
  'epoch': 2.8520208604954367,
  'step': 35000},
 {'loss': 0.21959974670410157,
  'grad_norm': 13.496240615844727,
  'learning_rate': 7.154498044328553e-07,
  'epoch': 2.8927640156453718,
  'step': 35500},
 {'loss': 0.22792927551269532,
  'grad_norm': 6.613856315612793,
  'learning_rate': 4.4382877009995657e-07,
  'epoch': 2.9335071707953064,
  'step': 36000},
 {'loss': 0.21724977111816407,
  'grad_norm': 8.921791076660156,
  'learning_rate': 1.722077357670578e-07,
  'epoch': 2.974250325945241,
  'step': 36500},
 {'eval_loss': 0.4890751242637634,
  'eval_accuracy': 0.8464595007641366,
  'eval_runtime': 16.2607,
  'eval_samples_per_second': 603.601,
  'eval_steps_per_second': 18.88,
  'epoch': 3.0,
  'step': 36816},
 {'train_runtime': 4931.6992,
  'train_samples_per_second': 238.884,
  'train_steps_per_second': 7.465,
  'total_flos': 5.433814602886219e+16,
  'train_loss': 0.36402171697372043,
  'epoch': 3.0,
  'step': 36816}]

In [32]:
matched_results = trainer.evaluate(
    eval_dataset=tokenized_mnli["validation_matched"],
    metric_key_prefix="mnli_matched"
)

matched_results

{'mnli_matched_loss': 0.4890751242637634,
 'mnli_matched_accuracy': 0.8464595007641366}

In [33]:
mismatched_results = trainer.evaluate(
    eval_dataset=tokenized_mnli["validation_mismatched"],
    metric_key_prefix="mnli_mismatched"
)

mismatched_results

{'mnli_mismatched_loss': 0.47448283433914185,
 'mnli_mismatched_accuracy': 0.8486574450772986}

In [34]:
FINAL_MODEL_DIR = "../models/fp32/final"

trainer.save_model(FINAL_MODEL_DIR)
tokenizer.save_pretrained(FINAL_MODEL_DIR)

print(f"FP32 model saved to: {FINAL_MODEL_DIR}")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

FP32 model saved to: ../models/fp32/final

In [37]:
log_df = pd.DataFrame(trainer.state.log_history)

TRAINING_LOG_PATH = "../results/mnli/fp32_training_log.csv"
log_df.to_csv(TRAINING_LOG_PATH, index=False)

print(f"Training log saved to: {TRAINING_LOG_PATH}")

log_df.tail()

Training log saved to: ../results/mnli/fp32_training_log.csv

,loss,grad_norm,learning_rate,epoch,step,eval_loss,eval_accuracy,eval_runtime,eval_samples_per_second,eval_steps_per_second,...,mnli_matched_loss,mnli_matched_accuracy,mnli_matched_runtime,mnli_matched_samples_per_second,mnli_matched_steps_per_second,mnli_mismatched_loss,mnli_mismatched_accuracy,mnli_mismatched_runtime,mnli_mismatched_samples_per_second,mnli_mismatched_steps_per_second
74,0.21725,8.921791,1.722077e-07,2.97425,36500,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,NaN,NaN,NaN,3.00000,36816,0.489075,0.84646,16.2607,603.601,18.88,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,NaN,NaN,NaN,3.00000,36816,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,NaN,NaN,NaN,3.00000,36816,NaN,NaN,NaN,NaN,NaN,...,0.489075,0.84646,16.1354,608.291,19.027,NaN,NaN,NaN,NaN,NaN
78,NaN,NaN,NaN,3.00000,36816,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.474483,0.848657,17.0302,577.327,18.085

In [39]:
mnli_results = {
    "matched": matched_results,
    "mismatched": mismatched_results,
}

RESULTS_PATH = "../results/mnli/fp32_results.json"

with open(RESULTS_PATH, "w") as f:
    json.dump(mnli_results, f, indent=4)

print(f"MNLI results saved to: {RESULTS_PATH}")

MNLI results saved to: ../results/mnli/fp32_results.json

In [40]:
trainer.save_state()

In [47]:
run_info = {
    "model": MODEL_NAME,
    "seed": SEED,
    "max_length": MAX_LENGTH,
    "learning_rate": LEARNING_RATE,
    "batch_size": BATCH_SIZE,
    "num_epochs": NUM_EPOCHS,
    "peak_gpu_memory_gb": peak_memory,
}

RUN_INFO_PATH = "../results/mnli/fp32_run_info.json"

with open(RUN_INFO_PATH, "w") as f:
    json.dump(run_info, f, indent=4)

run_info

{'model': 'google-bert/bert-base-uncased',
 'seed': 42,
 'max_length': 128,
 'learning_rate': 2e-05,
 'batch_size': 32,
 'num_epochs': 3,
 'peak_gpu_memory_gb': 3.741863250732422}