# IMPORTS

In [1]:
from datasets import load_dataset
import pandas as pd

# Load Dataset - HANS

In [2]:
HANS_URL = (
    "https://raw.githubusercontent.com/tommccoy1/hans/"
    "master/heuristics_evaluation_set.txt"
)

hans = load_dataset(
    "csv",
    data_files={"validation": HANS_URL},
    delimiter="\t"
)

hans

DatasetDict({
    validation: Dataset({
        features: ['gold_label', 'sentence1_binary_parse', 'sentence2_binary_parse', 'sentence1_parse', 'sentence2_parse', 'sentence1', 'sentence2', 'pairID', 'heuristic', 'subcase', 'template'],
        num_rows: 30000
    })
})

# Dataset Structure

In [3]:
hans["validation"].features

{'gold_label': Value('large_string'),
 'sentence1_binary_parse': Value('large_string'),
 'sentence2_binary_parse': Value('large_string'),
 'sentence1_parse': Value('large_string'),
 'sentence2_parse': Value('large_string'),
 'sentence1': Value('large_string'),
 'sentence2': Value('large_string'),
 'pairID': Value('large_string'),
 'heuristic': Value('large_string'),
 'subcase': Value('large_string'),
 'template': Value('large_string')}

In [4]:
hans["validation"][0]

{'gold_label': 'non-entailment',
 'sentence1_binary_parse': '( ( The president ) ( ( advised ( the doctor ) ) . ) )',
 'sentence2_binary_parse': '( ( The doctor ) ( ( advised ( the president ) ) . ) )',
 'sentence1_parse': '(ROOT (S (NP (DT The) (NN president)) (VP (VBD advised) (NP (DT the) (NN doctor))) (. .)))',
 'sentence2_parse': '(ROOT (S (NP (DT The) (NN doctor)) (VP (VBD advised) (NP (DT the) (NN president))) (. .)))',
 'sentence1': 'The president advised the doctor .',
 'sentence2': 'The doctor advised the president .',
 'pairID': 'ex0',
 'heuristic': 'lexical_overlap',
 'subcase': 'ln_subject/object_swap',
 'template': 'temp1'}

# Dataset distribution

In [5]:
print("Number of examples:", len(hans["validation"]))
print("Columns:", hans["validation"].column_names)

Number of examples: 30000
Columns: ['gold_label', 'sentence1_binary_parse', 'sentence2_binary_parse', 'sentence1_parse', 'sentence2_parse', 'sentence1', 'sentence2', 'pairID', 'heuristic', 'subcase', 'template']

In [6]:
df = hans["validation"].to_pandas()
print("Label distribution:\n")
print(df["gold_label"].value_counts())

print("Heuristic distribution:\n") 
print(df["heuristic"].value_counts())

print("\nNumber of subcases:", df["subcase"].nunique())
print("Number of templates:", df["template"].nunique())

Label distribution:

gold_label
non-entailment    15000
entailment        15000
Name: count, dtype: int64
Heuristic distribution:

heuristic
lexical_overlap    10000
subsequence        10000
constituent        10000
Name: count, dtype: int64

Number of subcases: 30
Number of templates: 60

# Heuristic and label distribution

In [7]:
pd.crosstab(df["heuristic"], df["gold_label"])

gold_label       entailment  non-entailment
heuristic
constituent            5000            5000
lexical_overlap        5000            5000
subsequence            5000            5000

# Subcase analysis

In [8]:
pd.crosstab(df["subcase"], df["gold_label"])

gold_label                      entailment  non-entailment
subcase
ce_adverb                             1000               0
ce_after_since_clause                 1000               0
ce_conjunction                        1000               0
ce_embedded_under_since               1000               0
ce_embedded_under_verb                1000               0
cn_adverb                                0            1000
cn_after_if_clause                       0            1000
cn_disjunction                           0            1000
cn_embedded_under_if                     0            1000
cn_embedded_under_verb                   0            1000
le_around_prepositional_phrase        1000               0
le_around_relative_clause             1000               0
le_conjunction                        1000               0
le_passive                            1000               0
le_relative_clause                    1000               0
ln_conjunction                           0            1000
ln_passive                               0            1000
ln_preposition                           0            1000
ln_relative_clause                       0            1000
ln_subject/object_swap                   0            1000
se_PP_on_obj                          1000               0
se_adjective                          1000               0
se_conjunction                        1000               0
se_relative_clause_on_obj             1000               0
se_understood_object                  1000               0
sn_NP/S                                  0            1000
sn_NP/Z                                  0            1000
sn_PP_on_subject                         0            1000
sn_past_participle                       0            1000
sn_relative_clause_on_subject            0            1000